version: 1.0.{build}
clone_folder: c:\src\es-theme-carbon
build_script:
- 7z a master.zip C:\src\es-theme-carbon
artifacts:
- path: master.zip
deploy:
- provider: GitHub
  tag: continuous
  release: continuous
  auth_token:
    secure: j2wYgDHRlxXaLB8MjsM3l2T+KlBA441m1r9g5cdo6nNh36f7w+iRlUv6eDtNB332
    
